# home-ssh-config.nix
#
# Home-manager module for SSH client config on l.
#
# Structure (split across files so each concern is easy to reason about):
#   - THIS file  — personal/local hosts (git forges, home routers, misc), the
#                  default `Host *` block, and the generator itself. It also
#                  defines the shared option `local.sshExtraConfig` that sibling
#                  modules append their Host blocks to.
#   - ./home-ssh-config-runpod.nix — NordLayer/RunPod jump hosts + dev/prod
#                  fleet + storage + the fleet-socks SOCKS helpers.
#   - ./home-ssh-config-nfb.nix    — NFB LADC VPN jump host + device aliases +
#                  Opengear serial-console aliases.
#
# Implementation:
#   - `ensure-ssh-runtime-dir` — creates /run/user/$UID/ssh/ at login (tmpfs
#     for ControlPath sockets so multiplexing avoids disk I/O).
#   - `generate-ssh-config` — writes ~/.ssh/config at login. We generate it
#     at login (instead of declaring it via `programs.ssh`) so we can embed
#     `$(id -u)` in `ControlPath` without hard-coding the UID at build time.
#   - Both scripts are invoked from `programs.bash.profileExtra`.
#
# The generated config order is: personal blocks (this file) -> everything in
# `local.sshExtraConfig` (sibling modules) -> the default `Host *` block LAST.

{ config, pkgs, lib, ... }:

{
  # Extension point: sibling modules append their Host blocks here. It is
  # spliced into the generated ~/.ssh/config after the personal blocks and
  # BEFORE the final `Host *` catch-all (which must stay last).
  options.local.sshExtraConfig = lib.mkOption {
    type = lib.types.lines;
    default = "";
    description = "Additional ssh_config Host blocks, concatenated before `Host *`.";
  };

  config = {
    home.packages = with pkgs; [
      # Create SSH control socket directory in tmpfs.
      (writeShellApplication {
        name = "ensure-ssh-runtime-dir";
        text = ''
          ssh_dir="/run/user/$(id -u)/ssh"
          if [ ! -d "$ssh_dir" ]; then
            mkdir -p "$ssh_dir"
            chmod 700 "$ssh_dir"
          fi
        '';
      })

      # Generate ~/.ssh/config with a dynamic UID in ControlPath.
      (writeShellApplication {
        name = "generate-ssh-config";
        text = ''
          ssh_config_dir="$HOME/.ssh"
          if [ ! -d "$ssh_config_dir" ]; then
            mkdir -p "$ssh_config_dir"
            chmod 700 "$ssh_config_dir"
          fi
          # Per-host known_hosts files (see UserKnownHostsFile in the
          # generated config) live under this directory.
          mkdir -p "$ssh_config_dir/known_hosts.d"
          chmod 700 "$ssh_config_dir/known_hosts.d"

          cat > "$ssh_config_dir/config" <<SSH_CONFIG_EOF
          #
          # .ssh/config
          #
          # Generated by generate-ssh-config (home-ssh-config.nix)
          # Sections come from home-ssh-config{,-runpod,-nfb}.nix
          #
          Host github.com
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_ed25519
            IdentitiesOnly yes

          Host github.com-runpod
            HostName github.com
            User git
            identityFile ~/.ssh/id_ed25519_runpod
            IdentitiesOnly yes

          Host dcops1
            hostname 160.72.7.94
            user siden

          Host ccl-miami-mgmt
            hostname 169.254.254.210
            user siden
            proxyjump dcops1

          Host homeqotom
            User das
            HostName 172.16.50.50
            LocalForward 8081 127.0.0.1:8081
            LocalForward 8082 127.0.0.1:80

          Host ex2200
            HostName 172.16.50.11
            User das
            #Legacy changes
            KexAlgorithms +diffie-hellman-group1-sha1
            Ciphers +aes128-cbc
            HostKeyAlgorithms=+ssh-rsa
            MACs hmac-sha1

          Host ex2200-2
            HostName 172.16.40.16
            User das
            #Legacy changes
            KexAlgorithms +diffie-hellman-group1-sha1
            Ciphers +aes128-cbc
            HostKeyAlgorithms=+ssh-rsa
            MACs hmac-sha1

          Host c9372
            HostName 172.16.40.72
            User das
            PubkeyAuthentication no
            PreferredAuthentications password

          Host z
            Hostname 148.100.85.152
            User linux1

          Host z2
            Hostname 148.100.85.145
            User linux1

          ${config.local.sshExtraConfig}
          Host *
            User das
            KeepAlive yes
            ServerAliveInterval 30
            Protocol 2
            UseRoaming no
            ForwardAgent yes
            # Modern Key Exchange Algorithms (Kex) - Prioritizes Post-Quantum (if available) and Curve25519
            KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256@libssh.org,curve25519-sha256,diffie-hellman-group-exchange-sha256
            # Modern Ciphers - Prioritizes ChaCha20 and AES-GCM (Authenticated Encryption)
            Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
            # Modern MACs - Prioritizes Encrypt-then-MAC (EtM) modes
            MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
            # temp hmac-md5
            #MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-md5
            # https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing
            ControlMaster auto
            # ControlPath uses /run/user/\$UID/ssh/ (tmpfs) to reduce I/O pressure
            # The directory is created dynamically at login via ensure-ssh-runtime-dir
            ControlPath /run/user/$(id -u)/ssh/master-%n-%r@%h:%p
            ControlPersist 10m
            Compression yes
            ConnectTimeout 10
            HashKnownHosts no
          SSH_CONFIG_EOF
          chmod 600 "$ssh_config_dir/config"
        '';
      })
    ];

    # Run the generators at login. Home-manager merges this with any other
    # profileExtra defined elsewhere.
    programs.bash.profileExtra = ''
      ensure-ssh-runtime-dir
      generate-ssh-config
    '';
  };
}
