# home-ssh-config.nix
#
# Home-manager module for SSH client config on l.
#
# Implementation:
#   - `ensure-ssh-runtime-dir` — creates /run/user/$UID/ssh/ at login (tmpfs
#     for ControlPath sockets so multiplexing avoids disk I/O).
#   - `generate-ssh-config` — writes ~/.ssh/config at login. We generate it
#     at login (instead of declaring it via `programs.ssh`) so we can embed
#     `$(id -u)` in `ControlPath` without hard-coding the UID at build time.
#   - Both scripts are invoked from `programs.bash.profileExtra`.
#
# Edit the heredoc below to add/remove host entries.

{ config, pkgs, lib, ... }:

{
  home.packages = with pkgs; [
    # Create SSH control socket directory in tmpfs.
    (writeShellApplication {
      name = "ensure-ssh-runtime-dir";
      text = ''
        ssh_dir="/run/user/$(id -u)/ssh"
        if [ ! -d "$ssh_dir" ]; then
          mkdir -p "$ssh_dir"
          chmod 700 "$ssh_dir"
        fi
      '';
    })

    # Generate ~/.ssh/config with a dynamic UID in ControlPath.
    (writeShellApplication {
      name = "generate-ssh-config";
      text = ''
        ssh_config_dir="$HOME/.ssh"
        if [ ! -d "$ssh_config_dir" ]; then
          mkdir -p "$ssh_config_dir"
          chmod 700 "$ssh_config_dir"
        fi
        # Per-host known_hosts files (see UserKnownHostsFile in the
        # generated config) live under this directory.
        mkdir -p "$ssh_config_dir/known_hosts.d"
        chmod 700 "$ssh_config_dir/known_hosts.d"

        cat > "$ssh_config_dir/config" <<SSH_CONFIG_EOF
#
# .ssh/config
#
# Generated by generate-ssh-config (home-ssh-config.nix)
#
Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_ed25519
  IdentitiesOnly yes

Host github.com-runpod
  HostName github.com
  User git
  identityFile ~/.ssh/id_ed25519_runpod
  IdentitiesOnly yes

Host dcops1
  hostname 160.72.7.94
  user siden

Host ccl-miami-mgmt
  hostname 169.254.254.210
  user siden
  proxyjump dcops1

Host homeqotom
  User das
  HostName 172.16.50.50
  LocalForward 8081 127.0.0.1:8081
  LocalForward 8082 127.0.0.1:80

# Jump entry into the NordLayer sandbox container on l.
# The container's sshd is reachable directly via the host-container veth at
# 10.99.0.2:22 from this machine (l) -- see desktop/l/nordlayer-sandbox.nix.
# Inside the sandbox, run "nordlayer connect GATEWAY" once, then any
# ProxyJump-ed host below traverses the VPN tunnel.
Host vpn-jump
  Hostname 10.99.0.2
  User vpn
  IdentityFile ~/.ssh/id_ed25519
  StrictHostKeyChecking accept-new
  UserKnownHostsFile ~/.ssh/known_hosts.d/vpn-jump
  ServerAliveInterval 30
  # Disable connection multiplexing on the proxy hops. Sharing one
  # master across many ProxyJump-ed destination ssh's (the prod fleet
  # has ~3500 hosts) produced sporadic channel races and "ssh eof
  # before prompt" at ~50% rate during 100-host fleet walks. Each
  # destination ssh gets a fresh handshake to vpn-jump now; costs
  # ~1 RTT extra per ssh, but yields 100% success instead of 50%.
  ControlMaster no
  ControlPath none

# RunPod test host behind the NordLayer VPN.
Host runpod-jump
  Hostname 44.197.169.91
  User ubuntu
  IdentityFile ~/.ssh/id_ed25519_runpod
  IdentitiesOnly yes
  ProxyJump vpn-jump
  # See vpn-jump above for the multiplex-on-jump-host rationale.
  # This is the inner proxy; every prod fleet ssh forwards through it.
  ControlMaster no
  ControlPath none

# RunPod dev jump host behind the same NordLayer VPN.
Host dev-runpod-jump
  Hostname dev-docssh.runpod.io
  User rp_das
  IdentityFile ~/.ssh/id_ed25519_runpod
  IdentitiesOnly yes
  ProxyJump vpn-jump
  # Match runpod-jump (above) for the dev fleet path.
  ControlMaster no
  ControlPath none

# RunPod dev internal targets reachable through the dev-runpod-jump host.
# Listed before the 100.* wildcard so these specific IPs match first.
Host 100.65.0.149 100.65.0.150 100.65.0.151 100.65.0.152
  User sshpower
  Port 2009
  IdentityFile ~/.ssh/id_rsa_runpod_dev
  IdentitiesOnly yes
  ProxyJump vpn-jump,dev-runpod-jump
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR

# RunPod internal targets reachable through the runpod-jump host
# (CGNAT 100.64.0.0/10 overlay). Long-form ssh command for any arbitrary
# RunPod IP — equivalent to what this block does, no config needed:
#   ssh -J vpn-jump,runpod-jump -i ~/.ssh/id_rsa_runpod -o IdentitiesOnly=yes \\
#       -o StrictHostKeyChecking=no -p 2009 sshpower@<IP>
# With this block: ssh 100.65.25.46
Host 100.*
  User sshpower
  Port 2009
  IdentityFile ~/.ssh/id_rsa_runpod
  IdentitiesOnly yes
  ProxyJump vpn-jump,runpod-jump
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR

Host ex2200
  HostName 172.16.50.11
  User das
  #Legacy changes
  KexAlgorithms +diffie-hellman-group1-sha1
  Ciphers +aes128-cbc
  HostKeyAlgorithms=+ssh-rsa
  MACs hmac-sha1

Host ex2200-2
  HostName 172.16.40.16
  User das
  #Legacy changes
  KexAlgorithms +diffie-hellman-group1-sha1
  Ciphers +aes128-cbc
  HostKeyAlgorithms=+ssh-rsa
  MACs hmac-sha1

Host c9372
  HostName 172.16.40.72
  User das
  PubkeyAuthentication no
  PreferredAuthentications password

Host z
  Hostname 148.100.85.152
  User linux1

Host z2
  Hostname 148.100.85.145
  User linux1

Host *
  User das
  KeepAlive yes
  ServerAliveInterval 30
  Protocol 2
  UseRoaming no
  ForwardAgent yes
  # Modern Key Exchange Algorithms (Kex) - Prioritizes Post-Quantum (if available) and Curve25519
  KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256@libssh.org,curve25519-sha256,diffie-hellman-group-exchange-sha256
  # Modern Ciphers - Prioritizes ChaCha20 and AES-GCM (Authenticated Encryption)
  Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
  # Modern MACs - Prioritizes Encrypt-then-MAC (EtM) modes
  MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
  # temp hmac-md5
  #MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-md5
  # https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing
  ControlMaster auto
  # ControlPath uses /run/user/$UID/ssh/ (tmpfs) to reduce I/O pressure
  # The directory is created dynamically at login via ensure-ssh-runtime-dir
  ControlPath /run/user/$(id -u)/ssh/master-%n-%r@%h:%p
  ControlPersist 10m
  Compression yes
  ConnectTimeout 10
  HashKnownHosts no
SSH_CONFIG_EOF
        chmod 600 "$ssh_config_dir/config"
      '';
    })
  ];

  # Run the generators at login. Home-manager merges this with any other
  # profileExtra defined elsewhere.
  programs.bash.profileExtra = ''
    ensure-ssh-runtime-dir
    generate-ssh-config
  '';
}
